# Generated by Django 3.2.2 on 2024-08-09 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ] #como es inicial, no depende de ninguna
#operaciones que se van a crear o a ejecutar
    operations = [
        migrations.CreateModel( #se va a crear un modelo
            name='Comic', #de nombre Comic
            fields=[ #campos que va a tener
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('marvel_id', models.PositiveIntegerField(unique=True, verbose_name='marvel id')),
                ('title', models.CharField(default='', max_length=120, verbose_name='title')),
                ('description', models.TextField(default='', verbose_name='description')),
                ('price', models.FloatField(default=0.0, max_length=5, verbose_name='price')),
                ('stock_qty', models.PositiveIntegerField(default=0, verbose_name='stock qty')),
                ('picture', models.URLField(default='', verbose_name='picture')),
            ],
            options={ #configuraciones, coincide con lo que declare en mi clase Meta (models.py)
                'verbose_name': 'comic',
                'verbose_name_plural': 'comics',
                'db_table': 'e_commerce_comics',
            },
        ),
    ]
