# Generated by Django 3.2.2 on 2024-08-16 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0002_wishlist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wishlist',
            options={'verbose_name': 'wish list', 'verbose_name_plural': 'wish lists'},
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='cart',
            field=models.BooleanField(default=False, verbose_name='cart'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='favorite',
            field=models.BooleanField(default=False, verbose_name='favorite'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='wished_qty',
            field=models.PositiveIntegerField(default=0, verbose_name='wished qty'),
        ),
        migrations.AlterModelTable(
            name='wishlist',
            table='e_commerce_wish_list',
        ),
    ]
